export const ICON_MAPPER: Record<string, string> = {
  'TanStack Router': '/icons/TansTack.png',
  'TanStack Start': '/icons/TansTack.png',
  Svelte: '/icons/Svelte.png',
  Solid: '/icons/solid.png',
  Nuxt: '/icons/nuxt.png',
  React: '/icons/react.png',
  Astro: '/icons/astro.png',
  'React Router': '/icons/ReactRouter.png',
  Zod: '/icons/zod-icon.png',
  Node: '/icons/nodejs.png',
  Cloudflare: '/icons/cloudflare.png',
  PostgreSQL: '/icons/postgresql.png',
  MySQL: '/icons/mysql.png',
  MongoDB: '/icons/mongodb.png',
  SQLite: '/icons/sqlite.png',
  Auth0: '/icons/auth_logo.png',
  JWT: '/icons/jwt.png',
  Stripe: '/icons/stripe.png',
  Polar: '/icons/polar.png',
  'Expo Bare': '/icons/expo.png',
  Prisma: '/icons/prisma.png',
  Drizzle: '/icons/drizzle.png',
  Mongoose: '/icons/mongoose.png',
  oRPC: '/icons/orpc.png',
  tRPC: '/icons/trpc.png',
  'Next.js': '/icons/nextjs.png',
  Vercel: '/icons/vercel.png',
  'Expo + Uniwind': '/icons/expo.png',
  'Expo + Unistyles': '/icons/expo.png',
  Git: '/icons/git.png',
  Turso: '/icons/turso.png',
  Supabase: '/icons/supabase.png',
  Docker: '/icons/docker.png',
  'MongoDB Atlas': '/icons/mongodb.png',
  Neon: '/icons/neon.png',
  PlanetScale: '/icons/planetscale.png',
  Fastify: '/icons/fastify.png',
  Hono: '/icons/hono.png',
  Convex: '/icons/convex.png',
  Express: '/icons/express.png',
  Elysia: '/icons/elysia.png',
  Bun: '/icons/bun.png',
  'Node.js': '/icons/nodejs.png',
  'Cloudflare Workers': '/icons/cloudflare.png',
  'Cloudflare D1': '/icons/cloudflare.png',
};
